### ISSUE TITLE
Splitting control plane from DaemonSet

### ISSUE THREAD

**Issue by CoufalJa** [vmware/kube-fluentd-operator#10]
Hi, this is some great stuff that I was missing for a long time. I have a question did you considered splitting the "control-plane" e.g. config-reloader out of the DaemonSet? It would be really powerful if one could use any compatible fluentd image with whatever plugins in a DaemonSet. Config reloader would take care of the configuration (which could be running as Deployment) while DaemonSet will do the heavy lifting sync could be done through ConfigMap/Secret (like prometheus-operator does). If that is a direction you guys would like to follow I am happy to work on a PR.

**Comment by jvassev** [comment]
Hi @CoufalJa 
I am happy you find this project useful.

The control plane is really decoupled from the fluentd: it just writes files to disk and can (optionally) force fluentd to reload its configuration. This is how the config-reloader is used: https://github.com/vmware/kube-fluentd-operator/blob/master/log-router/templates/daemonset.yaml#L51

You can integrate config-reloader into any fluentd as long as:
- both share a writeable volume
- fluentd has  `rpc_endpoint` enabled (to enable dynamic reloading)
- fluentd has the the plugins `fluent-plugin-detect-exceptions`, `fluent-plugin-rewrite-tag-filter`,  `fluent-plugin-kubernetes_metadata_filter`

Of the above three only the last is really a *hard* requirement because macro expansion uses these particular plugins and the generated files will not be valid without these plug-ins. The first two though can be worked-around (expose the rpc port, use [configmap-reload](https://github.com/jimmidyson/configmap-reload), etc)

The reason I chose a DaemonSet is it prevents fluentd running with a stale configuration. Now, you cannot stop the control plane without stopping the fluentd too.

However, you are right that now the control plane run on every node, performs the same calculations and generates the same files.

It would be nice to get rid of that but can it be done without introducing too much complexity?

**Comment by jvassev** [comment]
Closing this for now. We can discuss approaches going forward.
