### ISSUE TITLE
Config Reloading Process

### ISSUE THREAD

**Issue by nehalraf** [vmware/kube-fluentd-operator#14]
Hi guys, Thanks for this great project. I want to know if config-reloader restarts fluentd process or only reload configuration without restarting?

Thanks

**Comment by jvassev** [comment]
Hi,

This problem is solved by Fluentd already - we just make sure to orchestrate the process.

When a config change is detected (different sha256 sum) after post-processing and normalization, the files are written to disk an Fluentd is restarted over its RPC endpoint. Have a look at this: https://github.com/vmware/kube-fluentd-operator/blob/master/config-reloader/templates/fluent.conf#L6

As for tailing logs, a `pos_file` is configured for the Kubernetes pod logs. A pos file tracks how much of a file is already processed : https://docs.fluentd.org/v1.0/articles/in_tail#pos_file-(highly-recommended)

In general I think you are covered unless Fluentd or kube-fluentd-operator has a bug :)
