### ISSUE TITLE
detect_exceptions causing fluentd to delay the log push to sumologic

### ISSUE THREAD

**Issue by praveenk0535** [vmware/kube-fluentd-operator#142]
Hi,

We are trying to use the plugin (detect_exceptions) to concat java exceptions in a single line. Can you help on the config is I am missing anything which is causing the fluentd to delay the logs push to sumologic and seeing the below errors

2020-09-25 19:39:39 +0000 [warn]: #0 emit transaction failed: error_class=Fluent::Plugin::Buffer::BufferOverflowError error="buffer space has too many data" 

Fluentd Config:
{
	"fluent.conf": "<filter **>
		  @type detect_exceptions
		  multiline_flush_interval 0.1
		</filter>
		<match **>
		 @type sumologic
		    log_format json
		    endpoint xxxxxxxxxxxxxxxxxxxxxx
		    <buffer>
		        flush_mode immediate
		    </buffer>
		</match>"
}

Operator version : vmware/kube-fluentd-operator:v1.12.0

**Comment by Cryptophobia** [comment]
@praveenk0535 , did you figure this out?

**Comment by Cryptophobia** [comment]
Looks like there is a memory leak with the gems and config that you are using. Likely one of the filters is capturing too much and filling up the buffer. You may need to set more parameters in order to make sure this does not happen and the exception is sent together but as a raw message stream and filtered correctly:

```
      remove_tag_prefix raw
      message message
      stream stream
      languages java, python
  ```
