### ISSUE TITLE
Add support for exception detection

### ISSUE THREAD

**Issue by mhulscher** [vmware/kube-fluentd-operator#9]
I was wondering if the following plugin would be compatible with the way kube-fluentd-operator handles message routing. Being able to parse and forward multi-line exceptions would be a great feature.

https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions

**Comment by jvassev** [comment]
This seems like a very capable plugin - thanks for pointing it out.

One thing it requires is modifying the tag of the log events (`remove_tag_prefix`), otherwise it will create an infinite loop: the output of the plugin will be routed to the same plugin again. The problem with this is that the ** and $thisns macros will no longer work.

However we can workaround it with some rewriting and deeper changes. Imagine the user configured this:
```

<filter $labels(app=jpetstore)>
  @type detect_exceptions
  languages java, python
</filter>

<match **>
  @type null
</match>
```

Such a filter does not exists, but it can be rewritten as this:

```
# the match expression is calculated as before
<match namespace.*.*._labels.jpetstore>
  @type rewrite_tag

  # prefix the jpetstore stream with the name of the processor and some unique ID,
  # remember the ID for later
  prefix will_detect_exceptions.{UID}.${tag}

  # the only good value for the stream
  stream container_info
</match>

# process the exception stream
<match will_detect_exceptions.{ID}.namespace.*.*._labels.jpetstore>
  @type detect_exceptions
  
  # only remove the name of the processor, leaving the ID
  remove_tag_prefix will_detect_exceptions
  languages java, python
</match>

# at this point expand the expression namespace.** 
# to also include {ID}.**
<match {ID}.namespace.*.*.** namespace.*.*.**>
  @type null
</match>
```

**Comment by jvassev** [comment]
@mhulscher 
I've implemented the approach outlined above in the `detect-exceptions` branch and got some good results using this stacktrace I found on the internet: https://gist.github.com/jvassev/59d7616d601d9c19e23b328e591546d8

Can you test in your k8s cluster using the  image `jvassev/kube-fluentd-operator:det-exc` and see if you are happy with the output?

The only change you need to make to the fluentd-config map is to add this before your final <match> directive:
```
    <filter $labels(app=jpetstore)>
       @type detect_exceptions
       languages java
    </filter>
```
It assumes that the jpetstore app producing stacktraces but you can configure it the same way as the fluent-plugin-detect-exceptions plugin - just use <filter> instead of <match>.

**Comment by jvassev** [comment]
@mhulscher Do you think we can close this? any success with the `detect-exceptions` tag?

**Comment by mhulscher** [comment]
I have not yet been in a position to test this myself. The added test passes which inspires confidence. I suggest to merge and close. And thanks for paying attention to the suggestion!
